// <auto-generated />
using System;
using InformacioniSistemZU.MainDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformacioniSistemZU.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260122140204_Initial Migration Nikola")]
    partial class InitialMigrationNikola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InformacioniSistemZU.Models.Dijagnoza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dijagnoze");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Lekar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Pol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecijalnostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecijalnostId");

                    b.ToTable("Lekari");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Pacijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LekarId")
                        .HasColumnType("int");

                    b.Property<byte>("Pol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LekarId");

                    b.ToTable("Pacijenti");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Pregled", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DijagnozaId")
                        .HasColumnType("int");

                    b.Property<int?>("LekarId")
                        .HasColumnType("int");

                    b.Property<int?>("PacijentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DijagnozaId");

                    b.HasIndex("LekarId");

                    b.HasIndex("PacijentId");

                    b.ToTable("Pregledi");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Specijalnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specijalnosti");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Lekar", b =>
                {
                    b.HasOne("InformacioniSistemZU.Models.Specijalnost", "Specijalnost")
                        .WithMany()
                        .HasForeignKey("SpecijalnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specijalnost");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Pacijent", b =>
                {
                    b.HasOne("InformacioniSistemZU.Models.Lekar", "Lekar")
                        .WithMany("Pacijenti")
                        .HasForeignKey("LekarId");

                    b.Navigation("Lekar");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Pregled", b =>
                {
                    b.HasOne("InformacioniSistemZU.Models.Dijagnoza", "Dijagnoza")
                        .WithMany()
                        .HasForeignKey("DijagnozaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InformacioniSistemZU.Models.Lekar", "Lekar")
                        .WithMany("Pregledi")
                        .HasForeignKey("LekarId");

                    b.HasOne("InformacioniSistemZU.Models.Pacijent", "Pacijent")
                        .WithMany("Pregledi")
                        .HasForeignKey("PacijentId");

                    b.Navigation("Dijagnoza");

                    b.Navigation("Lekar");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Lekar", b =>
                {
                    b.Navigation("Pacijenti");

                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("InformacioniSistemZU.Models.Pacijent", b =>
                {
                    b.Navigation("Pregledi");
                });
#pragma warning restore 612, 618
        }
    }
}
